# Generated by Django 2.1.7 on 2019-04-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Page',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='titular',
            new_name='name',
        ),
    ]
