# Generated by Django 2.1.7 on 2019-03-31 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acorta', '0002_auto_20190331_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='short_name',
        ),
    ]
