# Generated by Django 2.1.7 on 2019-03-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('instrumento', models.CharField(max_length=32)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=32)),
                ('lugar', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=32)),
                ('concierto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.Concierto')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('estilo', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='concierto',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.Grupo'),
        ),
        migrations.AddField(
            model_name='componente',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.Grupo'),
        ),
    ]
