# Generated by Django 2.1.7 on 2019-05-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pueblo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('ident', models.CharField(max_length=32)),
                ('altitud', models.IntegerField()),
                ('latitud', models.IntegerField()),
                ('longitud', models.IntegerField()),
                ('prob_precipitacion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=32)),
                ('direc_viento', models.CharField(max_length=32)),
                ('vel_viento', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('max_sens_termica', models.IntegerField()),
                ('min_sens_termica', models.IntegerField()),
                ('max_hum_relativa', models.IntegerField()),
                ('min_hum_relativa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('titulo', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='pueblo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pueblo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Usuario'),
        ),
    ]
