# Generated by Django 2.1.7 on 2019-05-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pueblo_num_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='titulo',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
