# Generated by Django 2.1.7 on 2019-05-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_visitante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitante',
        ),
    ]
