# Generated by Django 2.1.7 on 2019-05-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pueblo',
            name='seleccionado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
