# Generated by Django 2.1.7 on 2019-05-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pueblo_seleccionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='color_fondo',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='color_letra',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tamaño',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
