# Generated by Django 2.1.7 on 2019-05-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190522_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pueblo',
            name='altitud',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pueblo',
            name='latitud',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pueblo',
            name='longitud',
            field=models.CharField(max_length=32),
        ),
    ]
